# Ansible Master
Vagrant.configure("2") do |config|
  config.vm.define "ginger" do |ginger|
   ginger.vm.box = "jasonc/centos7"
   ginger.vm.hostname = "ginger"
   ginger.vm.network "private_network", ip: "10.35.46.5"
   ginger.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
   ginger.vm.provision "shell", inline: <<-SHELL
        # Ensure running clen system - Update all packages
        sudo yum update -y
        sudo yum install epel-release -y
        sudo yum install yum-utils device-mapper-persistent-data lvm2 curl tree git elinks traceroute -y
   SHELL
 end

 config.vm.define "honey" do |honey|
  honey.vm.box = "jasonc/centos7"
  honey.vm.hostname = "honey"
  honey.vm.network "private_network", ip: "10.35.46.7"
  honey.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  honey.vm.provision "shell", inline: <<-SHELL
       # Ensure running clen system - Update all packages
       sudo yum update -y
       sudo yum install epel-release -y
       sudo yum update -y
  SHELL
 end

# Token - docker swarm join --token SWMTKN-1-0ujh055zeljwdm7mzn2khzhf3jcargtzt27l1wm4vs43p36kby-8b2ibctckks96mxengcfwiow5 192.168.1.154:2377
 config.vm.define "lemon" do |lemon|
  lemon.vm.box = "jasonc/centos7"
  lemon.vm.hostname = "lemon"
  lemon.vm.network "private_network", ip: "10.35.46.12"
  lemon.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  lemon.vm.provision "shell", inline: <<-SHELL
       # Ensure running clen system - Update all packages
       sudo yum update -y
       sudo yum install epel-release -y
       sudo yum update -y
  SHELL
 end
end
