# Docker Swarm Lab -

    # Configuration for Docker (Swarm Master)
    Vagrant.configure("2") do |config|
      config.vm.define "dckmgr1" do |dckmgr1|
       dckmgr1.vm.box = "jasonc/centos7"
       dckmgr1.vm.hostname = "dckmgr1"
       dckmgr1.vm.network "private_network", ip: "10.24.46.31"
       dckmgr1.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
       dckmgr1.vm.network "forwarded_port", guest: 80, host:9810
       dckmgr1.vm.provision "shell", inline: <<-SHELL
               sudo yum update -y
               sudo yum install epel-release -y
               sudo yum install yum-utils device-mapper-persistent-data lvm2 wget curl -y
               sudo usermod -aG docker vagrant
               sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
               sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
               sudo chmod +x /usr/local/bin/docker-compose
               sudo yum update -y
               sudo yum install docker-ce -y
               sudo systemctl enable docker && sudo systemctl start docker && sudo systemctl status docker
        SHELL
     end

     config.vm.define "dckmgr2" do |dckmgr2|
      dckmgr2.vm.box = "jasonc/centos7"
      dckmgr2.vm.hostname = "dckmgr2"
      dckmgr2.vm.network "private_network", ip: "10.24.46.33"
      dckmgr2.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      dckmgr2.vm.network "forwarded_port", guest: 80, host:9811
      dckmgr2.vm.provision "shell", inline: <<-SHELL
           sudo yum update -y
           sudo yum install epel-release -y
           sudo yum install yum-utils device-mapper-persistent-data lvm2 wget curl -y
           sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
           sudo yum update -y
           sudo yum install docker-ce -y
           sudo systemctl enable docker && sudo systemctl start docker && sudo systemctl status docker
        SHELL
     end

     config.vm.define "dckmgr3" do |dckmgr3|
      dckmgr3.vm.box = "jasonc/centos7"
      dckmgr3.vm.hostname = "dckmgr3"
      dckmgr3.vm.network "private_network", ip: "10.24.46.55"
      dckmgr3.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      dckmgr3.vm.network "forwarded_port", guest: 80, host:9812
      dckmgr3.vm.provision "shell", inline: <<-SHELL
           sudo yum update -y
           sudo yum install epel-release -y
           sudo yum install yum-utils device-mapper-persistent-data lvm2 wget curl -y
           sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
           sudo yum update -y
           sudo yum install docker-ce -y
           sudo systemctl enable docker && sudo systemctl start docker && sudo systemctl status docker
       SHELL
     end

     config.vm.define "wrk1" do |wrk1|
      wrk1.vm.box = "jasonc/centos7"
      wrk1.vm.hostname = "wrk1"
      wrk1.vm.network "private_network", ip: "10.24.46.38"
      wrk1.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      wrk1.vm.network "forwarded_port", guest: 80, host:9813
      wrk1.vm.provision "shell", inline: <<-SHELL
           sudo yum update -y
           sudo yum install epel-release -y
           sudo yum install yum-utils device-mapper-persistent-data lvm2 wget curl -y
           sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
           sudo yum update -y
           sudo yum install docker-ce -y
           sudo systemctl enable docker && sudo systemctl start docker && sudo systemctl status docker
       SHELL
     end

     config.vm.define "wrk2" do |wrk2|
      wrk2.vm.box = "jasonc/centos7"
      wrk2.vm.hostname = "wrk2"
      wrk2.vm.network "private_network", ip: "10.24.46.39"
      wrk2.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      wrk2.vm.network "forwarded_port", guest: 80, host:9815
      wrk2.vm.provision "shell", inline: <<-SHELL
           sudo yum update -y
           sudo yum install epel-release -y
           sudo yum install yum-utils device-mapper-persistent-data lvm2 wget curl -y
           sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
           sudo yum update -y
           sudo yum install docker-ce -y
           sudo systemctl enable docker && sudo systemctl start docker && sudo systemctl status docker
       SHELL
     end

     config.vm.define "wrk3" do |wrk3|
      wrk3.vm.box = "jasonc/centos7"
      wrk3.vm.hostname = "wrk3"
      wrk3.vm.network "private_network", ip: "10.24.46.42"
      wrk3.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      wrk3.vm.network "forwarded_port", guest: 80, host:9817
      wrk3.vm.provision "shell", inline: <<-SHELL
           sudo yum update -y
           sudo yum install epel-release -y
           sudo yum install yum-utils device-mapper-persistent-data lvm2 wget curl -y
           sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
           sudo yum update -y
           sudo yum install docker-ce -y
           sudo systemctl enable docker && sudo systemctl start docker && sudo systemctl status docker
       SHELL
     end

     config.vm.define "dcktest" do |dcktest|
      dcktest.vm.box = "jasonc/centos7"
      dcktest.vm.hostname = "dcktest"
      dcktest.vm.network "private_network", ip: "10.24.46.48"
      dcktest.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      dcktest.vm.network "forwarded_port", guest: 80, host:9819
      dcktest.vm.provision "shell", inline: <<-SHELL
           sudo yum update -y
           sudo yum install epel-release -y
           sudo yum install yum-utils device-mapper-persistent-data lvm2 wget curl -y
           sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
           sudo yum update -y
           sudo yum install docker-ce -y
           sudo systemctl enable docker && sudo systemctl start docker && sudo systemctl status docker
       SHELL
     end

     config.vm.define "citool" do |citool|
      citool.vm.box = "jasonc/centos7"
      citool.vm.hostname = "ci-tool"
      citool.vm.network "private_network", ip: "10.24.46.41"
      citool.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
      citool.vm.network "forwarded_port", guest: 80, host:9818
      citool.vm.provision "shell", inline: <<-SHELL
           sudo yum update -y
           sudo yum install epel-release -y
           sudo yum -y install java-1.8.0-openjdk.x86_64
           sudo cp /etc/profile /etc/profile_backupecho 'export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk' | sudo tee -a /etc/profileecho 'export JRE_HOME=/usr/lib/jvm/jre' | sudo tee -a /etc/profilesource /etc/profile
           cd ~
           sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
           sudo rpm --import http://pkg.jenkins-ci.org/redhat-stable/jenkins-ci.org.key
           sudo yum install jenkins -y
       SHELL
     end
    end
